import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useMutation, useQuery } from '@apollo/client'

import { CreateNewStudentDocument, GetOneStudentDocument, NewOrganizationDocument, StudentInputInput, StudentsDocument, StudentsQuery, StudentsQueryVariables } from '@/gql/graphql'
import { DataGrid, GridColDef, GridValueGetterParams } from '@mui/x-data-grid'
import { Box, Button, Divider, Input, Modal, Stack, TextField, Typography } from '@mui/material'
import { useState } from 'react'
import { Field, FieldArray, Form, FormLoader, getFieldProps, Reset, ResponseMessage, Submit } from 'apollo-form'
import * as Yup from 'yup';
import { useRouter } from 'next/router'

export default function EditStudent() {
    
    const router = useRouter()

    console.log(router.query.id);

    var id = router.query.id;

    console.log(Number(id));
    
    const { data, error, loading } = useQuery(GetOneStudentDocument, {
      variables: { id:  Number(id) },
    });

    if (error) {
      console.log('Error')
    }
  
    if (loading) {
      console.log('Loading')
    }

    const studentPage =  () => {
    router.push('/');
    };

  return (
    <>
      <Head>
        <title>Create New Student</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          
      <Button 
          variant="contained"
          onClick={studentPage}>
             Student Page
      </Button>

      <Stack direction='row'>
        <Typography> Student Identifier:   </Typography>
        <Typography> { data?.student?.studentIdentifier} </Typography>
      </Stack> 

      <Stack direction='row'>
        <Typography> Student Json:   </Typography>
        <Typography> { data?.student?.studentJson} </Typography>
      </Stack>  


    </>
  )
}
